apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxcm
data:
  nginx.conf: |
    user nginx nginx;
    worker_processes 1;
    error_log stderr warn;
    events { worker_connections 4096; }
    http {
      server {
        listen 80;
        # listen 443 ssl;
        # ssl_certificate /etc/nginx/ssl/public/nginx.crt;
        # ssl_certificate_key /etc/nginx/ssl/private/nginx.key;

        access_log /dev/stdout;
        location / {
          proxy_pass http://open5e-api.default.svc.cluster.local:8000;
          proxy_redirect off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Host $server_name;
          # proxy_set_header X-Google-Real-IP $remote_addr;
          # 86400 seconds (24 hours) is the maximum a server is allowed.
          proxy_send_timeout 86400s;
          proxy_read_timeout 86400s;
        }
        include /var/lib/nginx/extra/*.conf;
      }
      server {
        # expose /nginx_status but on a different port to avoid
        # external visibility / conflicts with the app.
        listen 8090;
        location /nginx_status {
          stub_status on;
          access_log off;
        }
        location / {
          root /dev/null;
        }
      }
    }
