apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: "TCP"
      port: 80
      name: http
      targetPort: 80
    # - protocol: "TCP"
    #   name: https
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        # - name: https
        #   containerPort: 443
        #   hostPort: 443
        volumeMounts:
        - name: nginx-volume
          mountPath: "/etc/nginx"
        # - name: servercert
        #   mountPath: "/etc/nginx/ssl/public"
        # - name: serverkey
        #   mountPath: "/etc/nginx/ssl/private"
      volumes:
        - name: nginx-volume
          configMap:
            name: nginxcm
            items:
              - key: nginx.conf
                path: nginx.conf
      #   - name: serverkey
      #     secret:
      #       secretName: open5e-api
      #       items:
      #         - key: SERVER_KEY
      #           path: nginx.key
      #   - name: servercert
      #     secret:
      #       secretName: open5e-api
      #       items:
      #         - key: SERVER_CRT
      #           path: nginx.crt
